<?php


namespace app\app2\commons;

use think\Facade;

class TestFacade extends Facade {

    protected static function getFacadeClass() {
        parent::getFacadeClass(); // TODO: Change the autogenerated stub
        return TestFacadeInstance::class;
    }
}